nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg

# nlp_engine_name: stanza
# models:
#   -
#     lang_code: en
#     model_name: en
#   -
#     lang_code: hi
#     model_name: hi

# nlp_engine_name: transformers
# models:
#   -
#     lang_code: hi
#     model_name:
#       spacy: xx_ent_wiki_sm
#       transformers: mirfan899/hindi-bert-ner


ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    NORP: NRP
    FAC: LOCATION
    LOC: LOCATION
    GPE: LOCATION
    LOCATION: LOCATION
    ORG: ORGANIZATION
    ORGANIZATION: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME

  low_confidence_score_multiplier: 0.4
  low_score_entity_names:
  -
  labels_to_ignore:
  - O
  - ORGANIZATION # Has many false positives
  - CARDINAL
  - EVENT
  - LANGUAGE
  - LAW
  - MONEY
  - ORDINAL
  - PERCENT
  - PRODUCT
  - QUANTITY
  - WORK_OF_ART
